# Generated by Django 3.2.7 on 2022-06-05 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mes', '0004_reclamation_manque_piece'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reclamation',
            new_name='Reclamation_Probleme_Maintenance',
        ),
    ]
