# Generated by Django 3.2.7 on 2022-06-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mes', '0005_rename_reclamation_reclamation_probleme_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation_Probleme_Quanlite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_probleme_qualite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
