# Generated by Django 3.2.7 on 2022-06-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0006_reclamation_probleme_quanlite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectif_production',
            old_name='limite',
            new_name='objectif',
        ),
    ]
