# Generated by Django 3.2.7 on 2022-06-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mes', '0008_produced_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produced_product_number',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_produced_number', to='accounts.equipe'),
        ),
    ]
